### ISSUE TITLE
Preparação de ambiente inicial

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#1]
Preparar ferramentas para execução de atividades:

Geral:
- Criar conta no GitHub
- Instalar git 

Monitores:
- Instalar IDE ou editor de texto e compiladores
- Criar conta no Neps Academy

Designers:
- Instalar ferramentas gráficas ou usar opções onlines.

Redatores:
- Criar conta no Overleaf

**Comment by FerrariusF** [comment]
Ok

**Comment by matt0a0** [comment]
Done

**Comment by terrycarver** [comment]
ok

**Comment by josicapela95** [comment]
ok
