### ISSUE TITLE
Preparação material encontro monitoria 25/03/2023

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#103]
Apresentações

Análise de algoritmos recursivos (@alex-repo-alves )
Backtracking (@pedrohsouza )
Two pointers (@FerrariusF )
Busca completa retrabalhado (@callmerockett )

**Comment by pedrohsouza** [comment]
Ok

**Comment by FerrariusF** [comment]
ok

**Comment by alex-repo-alves** [comment]
Ok
