### ISSUE TITLE
Encontro Monitoria 01/04/2023

### ISSUE THREAD

**Issue by matt0a0** [filrpe/treinamento-OBI-2023#121]
Conteúdo abordado:

Possível falta dia 03/04/2023 : Possível atentado durante o período de aulas

Assuntos : 
-  Pilha de chamadas e Funções Recursivas
-

**Comment by pedrohsouza** [comment]
Ok

**Comment by FerrariusF** [comment]
ok

**Comment by alex-repo-alves** [comment]
Ok
