### ISSUE TITLE
Técnicas de programação

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#156]
- [x] #159
- [x] #160
- [x] #161
- [x] #162
- [x] #163
- [ ] Small to Large Merge
- [x] #164
- [x] #165

**Comment by callmerockett** [comment]
@pedrohsouza  @veecstart @alex-repo-alves @FerrariusF @filrpe mandem o ok

**Comment by FerrariusF** [comment]
ok

**Comment by pedrohsouza** [comment]
Ok

**Comment by alex-repo-alves** [comment]
Ok

**Comment by callmerockett** [comment]
@filiperib98
