### ISSUE TITLE
Resolução de problemas de programação básica do CodCad

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#16]
Tarefa: 
- Colocar as soluções na planilha do codcad.

Conteúdo do curso:

- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21

**Comment by FerrariusF** [comment]
ok

**Comment by callmerockett** [comment]
Atuação no slide de treinamento da monitoria:

@FerrariusF  - Vetores e Matrizes
@filrpe  - Cadeia de caracteres e strings
@veecstart  - Funções e funções recursivas
@callmerockett  - Introdução, Neps Academy, Entrada e saída em C++, Controle de Fluxo

**Comment by callmerockett** [comment]
Orientações pra alteração do slide:

- Iniciar com um problema
- Destacar como o conhecimento prévio não é suficiente
- Falar sobre uma funcionalidade nova necessária
- Por fim, introduzir a teoria

**Comment by callmerockett** [comment]
Fechando a tarefa, devido ao início da nova lista de resolução de problemas. Quem for resolvendo as antigas vai mandando oks pra computar a CH.

**Comment by pedrohsouza** [comment]
Ok

**Comment by alex-repo-alves** [comment]
Ok
