### ISSUE TITLE
Programação Básica: Controlando o Código

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#18]
Resolver os problemas da seção de Controlando o Código do CodCad: https://neps.academy/br/course/programacao-basica-(codcad)

- [x] #176
- [x] #177
- [x] #178
- [x] #179

**Comment by FerrariusF** [comment]
ok

**Comment by pedrohsouza** [comment]
Ok

**Comment by alex-repo-alves** [comment]
Ok

**Comment by matt0a0** [comment]
ok

**Comment by Mauesjr** [comment]
ok
