### ISSUE TITLE
Programação Básica: Vetores e Matrizes.

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#19]
Resolver os problemas da seção de "Vetores e Matrizes" do CodCad: https://neps.academy/br/course/programacao-basica-(codcad)

- [x] #180
- [x] #181

**Comment by FerrariusF** [comment]
ok

**Comment by pedrohsouza** [comment]
Ok

**Comment by alex-repo-alves** [comment]
Ok

**Comment by matt0a0** [comment]
ok
