### ISSUE TITLE
Seleção de representante de Design da equipe

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#2]
Funções 
- Ter contato direto com fontes externas de demanda
- Comunicar demandas externas nas reuniões da equipe

**Comment by terrycarver** [comment]
alou

**Comment by matt0a0** [comment]
### Notas da Tarefa
- [x] Briefing Inicial
- [ ] Perguntas Gerais
- [ ] Preferências de Design
- [ ] Adoção Do Canvas como modelo de edição Inicial

**Comment by josicapela95** [comment]
Ok

**Comment by callmerockett** [comment]
Representante escolhido: Matheus Souza.
