### ISSUE TITLE
Programação Básica: Cadeia de Caracteres.

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#20]
Resolver os problemas da seção de "Cadeia de Caracteres" do CodCad: https://neps.academy/br/course/programacao-basica-(codcad)

- [x] #182
- [x] #183

**Comment by FerrariusF** [comment]
ok

**Comment by pedrohsouza** [comment]
Ok

**Comment by alex-repo-alves** [comment]
Ok
