### ISSUE TITLE
Programação Básica: Funções e Ordenação.

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#21]
Resolver os problemas da seção de "Funções e Ordenação" do CodCad: https://neps.academy/br/course/programacao-basica-(codcad)

- [x] #184
- [x] #185
- [x] #186

**Comment by FerrariusF** [comment]
ok

**Comment by alex-repo-alves** [comment]
Ok

**Comment by pedrohsouza** [comment]
ok
