### ISSUE TITLE
Material de divulgação: Texto

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#23]
Produção do texto para o material de divulgação.

**Comment by Mauesjr** [comment]
ok

**Comment by matt0a0** [comment]
Convite Médio (redes sociais):

Você gosta de informática ou programação, mas sente que poderia evoluir mais e não sabe como.
Para auxiliar na sua evolução está aberto as inscrições para o treinamento da Olimpíada Brasileira de Informática (OBI) 2023 que além de auxiliar para aprimorar seus 
conhecimentos pode fazer você conquistar algumas medalhas.

Saiba mais em: (inserir link para o site do ifpa com a matéria e maiores informações)

Para site do IFPA:

Entre os dias (inserir período de inscrição) de fevereiro estarão abertas as inscrições para o Treinamento OBI 2023. O treinamento é destinado a estudantes do IFPA, do ensino médio ou primeiro ano da graduação, que tenham interesse em informática ou programação. Não é necessário conhecimento prévio nesses assuntos.

O treinamento ocorrerá de março a junho, com (inserir a quantidade de encontro semanais), onde será ensinado desde o básico da programação até o avançado, além do encontro semanal, desafios semanais serão propostos para otimizar o treinamento. No total, são (número de vagas) , distribuídas em (inserir turnos, caso houver mais de uma turma, dias da semana e horário). 

Para se inscrever no treinamento basta preencher o seguinte formulário( Inscrições Treinamento OBI 2023 - Formulários Google)
