### ISSUE TITLE
Melhoria de material da monitoria

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#30]
O material para os alunos vai ser uma versão mais enxuta do material dos monitores, sendo necessário aumentar o conteúdo inicial do treinamento da monitoria.

Subtarefas:

- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45

#### Orientações pra alteração do slide (Quando aplicável):

- Iniciar com um problema
- Destacar como o conhecimento prévio não é suficiente
- Falar sobre uma funcionalidade nova necessária
- Por fim, introduzir a teoria

**Comment by FerrariusF** [comment]
ok

**Comment by callmerockett** [comment]
@alex-repo-alves @pedrohsouza

**Comment by pedrohsouza** [comment]
Ok

**Comment by alex-repo-alves** [comment]
Ok
