### ISSUE TITLE
Banner para divulgação no site do IFPA

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#34]
Dar uma olhada no [portal do ifpa](https://ifpa.edu.br/index.php) e em como eles colocam os Banners deles (resolução), e criar um nosso inspirado nesse padrão (exemplo: https://ifpa.edu.br/component/content/article?id=1950), com as seguintes informações;

- Período de inscrições: de 06 a 22 de Fevereiro.
- Texto de chamada para o treinamento.
- Logo abaixo o link do nosso formulário de inscrições (ou QR code, dá pra gerar em ferramentas online)
- Sugestão de paleta de cores: Verde escuro com a logo branca do ifpa, porém não obrigatório. Fica a critério.

**Comment by terrycarver** [comment]
ok
