### ISSUE TITLE
Moodboard para produção da logo

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#36]
Montar um moodboard com os seguintes temas : Tecnologia/Ciências/Olimpiadas/Universidades/Programação e afins. Montar uma relação das logos de treinamentos que tem por aí da OBI seja dos times ou cursos. Exemplos: logo da OBI, MaratonUSP, Maratona CIn-UFPE, GEMA - USP, NOIC etc. Mas o foco é OBI.

OBS: **Utilizar o Figma.**

**Comment by Mauesjr** [comment]
ok
