### ISSUE TITLE
Montar formulário de inscrição para o treinamento

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#4]

**Comment by matt0a0** [comment]
- [x] Formulário Pronto
- [x] Avaliação do formulário
- Formulário : https://forms.gle/oBwWvyaFFDzKGA6D9

**Comment by callmerockett** [comment]
@veecstart alguns pontos sobre o formulário,:

- [x] Não é bom colocar modalidade/nível nesse primeiro formulário, a gente tem que assumir que os alunos não conhecem nada da OBI. Então tem que trocar os níveis por "1º ano do ensino médio" etc... até o quarto ano do ensino técnico, e adicionar "primeiro ano do ensino superior".
- [x] Não interessa pra gente o gênero do aluno, tem que remover esse campo.
- [x] Não interessa pra gente o ano de nascimento do aluno.
- [x] Adiciona uma pergunta se o aluno já participou de alguma olimpíada antes, e se sim, qual ou quais. É bom colocar as opções pro aluno ir marcando.
- [x] Adiciona uma pergunta se o aluno já sabe programar antes. Se sim, colocar pro aluno marcar as linguagens. 
- [x] Tem que deixar o título consistente, tudo treinamento. 
- [x] A descrição a gente pode ver depois, mas vamos ter que alterar também.

**Comment by matt0a0** [comment]
Algumas informações dizem a respeito do formato da pré inscrição na OBI em si, creio que para desenvolver artigos, uma base de dados com a idade dos participantes e gênero tenham sua utilidade, porém irei refazer

**Comment by callmerockett** [comment]
> Algumas informações dizem a respeito do formato da pré inscrição na OBI em si, creio que para desenvolver artigos, uma base de dados com a idade dos participantes e gênero tenham sua utilidade, porém irei refazer

Tem dois pontos a se analisar, o primeiro é que a inscrição pro treinamento que a UFPA vai fazer é independente das inscrições pra OBI. Quem faz o cadastro da escola pra OBI é o professor, que vai ser o coordenador local da OBI. A gente pode auxiliar o professor com isso, mas não tá no escopo original do projeto. A própria organização da OBI já faz esse papel de tirar dúvidas e dar orientações na inscrição.

O segundo ponto é a responsabilidade com informação pessoal, não tem nenhum motivo pra gente coletar esses tipos de dados. Se não temos um fim para aquilo, então não é justificável pedir. Se em algum momento mais pra frente essas informações se tornarem importantes a gente pode criar outros formulários, explicando por que a gente precisa daquela informação. Mas por ora é isso.

**Comment by matt0a0** [comment]
Updated @callmerockett

**Comment by callmerockett** [comment]
@veecstart, alguns pontos pra alterar:

O texto
> Formulário para os interessados em participar do treinamento em programação competitiva com objetivo em participar da Olimpíada Brasileira de Informática em 2023

Altera pra: "Inscrições para o treinamento para olimpíada brasileira de informática 2023". O motivo dessa alteração é ter pouco termo "novo". A gente vai distinguir programação competitiva de programação normal durante o treinamento.

Na pergunta das olimpíadas faltou a maior de todas, a OBM/OBMEP. E a opção "Nunca participei antes" tem que ser a primeira.

Tem que trocar a pergunta "Já programou em alguma linguagem antes?" por "Já usou alguma linguagem de programação antes? Quais?", daí tu coloca pra marcar múltiplas opções também. O motivo é que quem nunca programou antes pode nem entender a pergunta, por não saber o que é uma linguagem de programação.

Último ponto: Coloca o email logo abaixo do nome completo.

Depois dessas alterações a primeira versão do formulário já vai estar fina.

**Comment by matt0a0** [comment]
Agora eu acho que foi

**Comment by callmerockett** [comment]
Boa @veecstart , safe.
