### ISSUE TITLE
Revisar regulamento da OBI

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#54]
Pesquisar:
- Qual ambiente (SO, processador) os programas serão executados.
- Verificar se tem compensação de tempo para diferentes linguagens
- Versões permitidas das linguagens (C++)

OBS: Se essa informação não estiver disponível no regulamento, enviar email para a organização.

**Comment by FerrariusF** [comment]
Ok

**Comment by FerrariusF** [comment]
C++: Compilador G++ versão 9.3.0 ou superior - Linha de comando: g++ -std=gnu++17 -O2 -static -o executavel programa.cpp

**Comment by FerrariusF** [comment]
"Os programas submetidos pelos competidores serão compilados em ambiente Linux."
