### ISSUE TITLE
O que são Pull Requests no Github e como funciona o processo de revisõa

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#59]
Atividade de preparação da equipe.

**Comment by FerrariusF** [comment]
ok

**Comment by callmerockett** [comment]
@FerrariusF Depois separa o material de array do slide principal e faz um Pull Request pro repositório pra praticar. Depois faz **outro** Pull Request pra colocar a introdução. A revisão de quarta feira a gente já faz pela plataforma.

**Comment by filiperib98** [comment]
Ok
