### ISSUE TITLE
Resolução de problemas - Análise de algoritmos

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#73]
Essa tarefa é para praticar a análise de algoritmos nas soluções desenvolvidas enquanto expõe novos desafios não triviais. Ao todo serão 9 problemas.

- [x] #74
- [x] #75
- [x] #76

**Comment by FerrariusF** [comment]
ok

**Comment by pedrohsouza** [comment]
Ok
