### ISSUE TITLE
Pesquisar sobre manipulação do histórico local do repositório git

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#95]
Para ganhar experiência na manipulação do repositório local, pesquisar por:

- `git commit --amend`
- `git rebase` e suas opções
- `git cherry-pick`

Responder as perguntas:

- Quais as consequências de alterar o histórico de commits de uma branch que já está no repositório remoto?
- Qual a diferença entre branchs e commits?

**Comment by FerrariusF** [comment]
ok
