### ISSUE TITLE
Preparação de material para encontro da monitoria - 18/03/2023

### ISSUE THREAD

**Issue by callmerockett** [filrpe/treinamento-OBI-2023#97]
- Técnicas de programação:
  - Array de soma de prefixos - @veecstart 
  - Backtracking (força bruta com "poda") - @pedrohsouza
  - Busca binária - @ferrariusf

- Introdução a paradigmas de resolução de problemas, parte 1 - @callmerockett: 
  - Busca completa
  - Algoritmos Gulosos (se der tempo)

Orientações:
- **No máximo 40 min**
- Agenda sugerida:
  - Problema motivacional.
  - Apresentar solução "força bruta" (que provavelmente não resolve o problema).
  - Identificar as limitações da solução por força bruta.
  - Mostrar a técnica e como ela resolve os problemas da solução anterior.
  - Analisar complexidade temporal e espacial.

**Comment by FerrariusF** [comment]
ok

**Comment by callmerockett** [comment]
Depois fazer um PR com o material pro repositório para iniciar a revisão. @FerrariusF @veecstart
